version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my-snippets
    ports:
      - "3306:3306"

  pma:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db


