mutation register($registerUser: InputRegisterUser!) {
    register(registerUser: $registerUser) {
        jwt
        user {
            username
            email
            id
            confirmed
            createdAt
        }
    }
}