mutation signIn($signUser: InputSignUser!) {
    signIn(signUser: $signUser) {
        jwt
        user {
            id
            username
            email
            confirmed
            createdAt
        }
    }
}